version: '3'

volumes:
    broker_1: {}
    broker_2: {}
    broker_3: {}

services:

    broker-1:
        image: dalongrong/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26500:26500
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=0
            - ZEEBE_PARTITIONS_COUNT=3
            - ZEEBE_CLUSTER_SIZE=3
            - ZEEBE_REPLICATION_FACTOR=3
        volumes:
            - broker_1:/usr/local/zeebe/data

    broker-2:
        image: dalongrong/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26510:26500
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=1
            - ZEEBE_PARTITIONS_COUNT=3
            - ZEEBE_CLUSTER_SIZE=3
            - ZEEBE_REPLICATION_FACTOR=3
            - ZEEBE_CONTACT_POINTS=broker-1:26502
        volumes:
            - broker_2:/usr/local/zeebe/data

    broker-3:
        image: dalongrong/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26520:26500
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=2
            - ZEEBE_PARTITIONS_COUNT=3
            - ZEEBE_CLUSTER_SIZE=3
            - ZEEBE_REPLICATION_FACTOR=3
            - ZEEBE_CONTACT_POINTS=broker-1:26502
        volumes:
            - broker_3:/usr/local/zeebe/data
